### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ap-chehov** [TKoestlerx/sdexperiments#1]
Error loading script: outpaint_region.py
Traceback (most recent call last):
  File "D:\stable-diffusion-webui\modules\scripts.py", line 157, in load_scripts
    compiled = compile(text, scriptfile.path, 'exec')
  File "D:\stable-diffusion-webui\scripts\outpaint_region.py", line 69
    <title>sdexperiments/outpaint_region.py at main · TKoestlerx/sdexperiments</title>
                                                    ^
SyntaxError: invalid character '·' (U+00B7)

**Comment by TKoestlerx** [comment]
Ich würde auf einen fehlerhaften download tippen. Das sollte nicht in an dieser Stelle der Datei stehen. Versuch mal das zip file herunterzuladen.

**Comment by ap-chehov** [comment]
thanks, working

**Comment by ap-chehov** [comment]
![Безымянный-1](https://user-images.githubusercontent.com/113781631/197374840-b559e7b9-49a7-4afd-894f-745d3c8427c6.jpg)

**Comment by TKoestlerx** [comment]
Cool :)
