### ISSUE TITLE
[Feature Request] Add support for darkmode

### ISSUE THREAD

**Issue by Ladypoly** [TKoestlerx/sdexperiments#11]
When using darkmode the buttons are not really visible.
Please add an inverted color option for darkmode ui.
![ACanvas](https://user-images.githubusercontent.com/37795467/201545833-b7a9d6ae-7d41-4183-b328-325ed4a7830d.png)

**Comment by TKoestlerx** [comment]
I have used the standard gradio classes for most styles now. At least it should work better with that.
