### ISSUE TITLE
outpaint has Poor effect

### ISSUE THREAD

**Issue by ziyaxuanyi** [TKoestlerx/sdexperiments#12]
for the inpainting,outpaint has poor effect.
At the expanded junction, there is a clear sense of separation.
when use Outpainting mk2 script,it works well.

**Comment by TKoestlerx** [comment]
If you do the outpainting in the img2img Tab, it will use the same noise function as Outpainting mk2. (fft based on image content). But with the drawback that the black color is used as a mask.

Outpainting in the inpainting Tab will use the noise defined in the gradio ui. 
"latent nothing"  as noise-choice will lead to an identical image as the same seed in txt2img (if everything is masked and 1.0noise)
"latent noise" will give "wilder" variations.
And with the 1.5-inpainting model i get really good outpainting results in the inpainting tab too. However, non-inpainting models are much better with the fft-based noise.

But no matter if I do the outpainting based on fft noise or using the std types.... In most cases it needs a 2nd pass of inpainting with low-cfg to make the transitions clean.
