### ISSUE TITLE
No Show\Hide button

### ISSUE THREAD

**Issue by zvit** [TKoestlerx/sdexperiments#5]
I don't get a Show\Hide button under the script bar. Using Chrome, latest version.

**Comment by TKoestlerx** [comment]
But you have the Script itself in the script selection and where able to select it?

**Comment by zvit** [comment]
> But you have the Script itself in the script selection and where able to select it?

Correct.

**Comment by TKoestlerx** [comment]
I just had the same experience.
The button was suddenly no longer there.

Apparently the script reload at the webui does not work correctly. After I have restarted the WebUI once completely, everything is there again.

I suppose you have also made a reset via the UI?

**Comment by zvit** [comment]
Even after resetting it yesterday, it didn't appear. However, I just opened it now, and it's showing! I will test it out during the day and report any issues. Thanks! I guess you can close this case for now.
