### ISSUE TITLE
Text unreadable when dark mode in Windows is enabled

### ISSUE THREAD

**Issue by Thurion** [TKoestlerx/sdexperiments#6]
I'm using latest version of the script that is currently available (84567ca) and I noticed that the text in the canvas is not readable with dark mode enabled in Windows 10. I tested it in Firefox and Brave.

![unknown](https://user-images.githubusercontent.com/658665/199142786-f2149a98-d1df-4117-aa0c-c0ab6e0ed0f6.png)

**Comment by TKoestlerx** [comment]
The text should now be black in darkmode too.

**Comment by Thurion** [comment]
Looks good 👍
