### ISSUE TITLE
Alphamask not available in Script list

### ISSUE THREAD

**Issue by Kallamamran** [TKoestlerx/sdexperiments#7]
I have copied the script to scripts and restarted. It still doesn't show up in img2img-scripts-dropdown

![image](https://user-images.githubusercontent.com/25354644/199272045-a7cd58f8-933f-4839-b0dd-56314367b0f5.png)

![image](https://user-images.githubusercontent.com/25354644/199271975-33d7bcf3-7a07-4657-bb8f-1d1a1145f337.png)

**Comment by TKoestlerx** [comment]
This is the first time I have seen this behavior.
Is this after a complete restart or just the gradio UI reset?

**Comment by cjay777xb** [comment]
I get the same error after completely shutting browser and the environment.

I found this error in the startup:

  File "C:\stable-diffusion-webui-master\scripts\outpaint_region.py", line 69
    <title>sdexperiments/outpaint_region.py at alphacanvas · TKoestlerx/sdexperiments</title>

but that seems to only be about the. in the line.  I took it out anyway and resaved and that error went away.  But a new error came up:

  File "C:\stable-diffusion-webui-master\scripts\outpaint_region.py", line 1
    <!doctype html>
    ^
SyntaxError: invalid syntax

That one is hard explain as that's a v5 correct usage, but it could be throwing something off later in the script?

**Comment by TKoestlerx** [comment]
Please download the zip file and extract the script from there.

It seems like the downloaded File has markup Text that should not be in this file.
"
import math

import numpy as np
import skimage
"
should be the first few lines of the script.

**Comment by Kallamamran** [comment]
@cjay777xb 
This error was after a complete restart of both SD and the browser.

@TKoestlerx 
Aha... So that's what the error "regarding a not supported character  · " starting up is from 😊👍 That should explain things
![image](https://user-images.githubusercontent.com/25354644/199499422-1d38bbac-369d-45e5-ac92-79ac2ca1c4d3.png)
I will try it by ZIP or otherwise just rename the  · - thing in the py-script. Should work

Thank you both for replying!

**Comment by Kallamamran** [comment]
![image](https://user-images.githubusercontent.com/25354644/199593405-028d8253-1d0c-4793-8b8b-d3d6fa3dd80a.png)

This is what I meant

**Comment by Kallamamran** [comment]
Changed the strange dot for a hyphen and now I get this instead:

![image](https://user-images.githubusercontent.com/25354644/199597228-2014dc31-45df-4f03-8a01-2b7db30a4c57.png)

**Comment by TKoestlerx** [comment]
Thats still the wrong File.
The first few lines of the script need to look like this:

![alca](https://user-images.githubusercontent.com/86352149/199597802-6a23077e-f351-4648-bc16-39f554604b23.jpg)

I think the browser has added the markup of that page into the downloaded script.
Please try to download the zip file and use the script inside.

**Comment by Kallamamran** [comment]
Aha 😂 "Save link as" did not work 😏
Copied the code to the file manually and now it works!!

**Comment by TKoestlerx** [comment]
Indeed. 

I have also just tried this out. So if github still adds the whole page when downloading, it should not save it as .py... that's not a .py ;)
